services:
  server:
    build: ./server
    ports:
      - 5050:5000
    volumes:
      - ./server:/app
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - server
